#ifndef CLEARCHAIN_DISPLAY_PROTOCOL_H
#define CLEARCHAIN_DISPLAY_PROTOCOL_H

#include <stdint.h>

#define CLEARCHAIN_DISPLAY_PROTOCOL_VERSION 1U
#define CLEARCHAIN_DISPLAY_HEADER_SIZE 3U
#define CLEARCHAIN_DISPLAY_MAX_PACKET_SIZE 5U
#define CLEARCHAIN_DISPLAY_MIN_STAGE 1U
#define CLEARCHAIN_DISPLAY_MAX_STAGE 5U
#define CLEARCHAIN_RISK_SCORE_UNKNOWN 0xFFU

/* The wire format is version, command, payload length, then payload bytes. */
typedef enum {
    CLEARCHAIN_DISPLAY_CMD_WAITING = 1,
    CLEARCHAIN_DISPLAY_CMD_STAGE_CHANGED = 2,
    CLEARCHAIN_DISPLAY_CMD_SCAN_PROGRESS = 3,
    CLEARCHAIN_DISPLAY_CMD_RESULT = 4
} clearchain_display_command_t;

typedef enum {
    CLEARCHAIN_DISPLAY_RESULT_APPROVED = 0,
    CLEARCHAIN_DISPLAY_RESULT_MONITOR = 1,
    CLEARCHAIN_DISPLAY_RESULT_REJECT = 2,
    CLEARCHAIN_DISPLAY_RESULT_UNKNOWN = 3
} clearchain_display_result_t;

#endif
