#ifndef CLEARCHAIN_LCD_CONFIG_H
#define CLEARCHAIN_LCD_CONFIG_H
#define CLEARCHAIN_LCD_WIDTH 320U
#define CLEARCHAIN_LCD_HEIGHT 480U
#define CLEARCHAIN_LCD_SPI_MHZ 2U
#define CLEARCHAIN_LCD_SCK 7U
#define CLEARCHAIN_LCD_MOSI 9U
#define CLEARCHAIN_LCD_CS 8U
#define CLEARCHAIN_LCD_DC 1U
#define CLEARCHAIN_LCD_RESET 14U
#define CLEARCHAIN_LCD_MADCTL 0x48U
#if CLEARCHAIN_LCD_SPI_MHZ > 15 || CLEARCHAIN_LCD_SPI_MHZ < 1
#error "ST7796 SPI must be between 1 and 15 MHz"
#endif
#endif
